"""
Шаблон для ID файлов с Google Drive.
Для каждого мода вставьте ID из ссылки на файл.
Пример ссылки: https://drive.google.com/file/d/1xyzABC.../view
ID это часть между /d/ и /view
"""

drive_ids = {
    # GAME
    "color-blind_friendly": "",  # # Color-blind friendly (Color-blind friendly.vpk)
    "haze_ball": "",  # # Haze Ball (Haze Ball.vpk)
    "interloper": "",  # # Interloper (Interloper.vpk)
    "neonprime_shop": "",  # # NeonPrime Shop (NeonPrime Shop.vpk)
    "orange_lane_restored": "",  # # Orange Lane Restored (Orange Lane Restored.vpk)

    # HEROES
    "dota_2_juggernaut_voice_for_abrams": "",  # # Dota 2 Juggernaut voice for Abrams (Dota 2 Juggernaut voice for Abrams.vpk)
    "abrams_bull": "",  # # Abrams Bull (Abrams Bull.vpk)
    "abrams_doomguy": "",  # # Abrams Doomguy (Abrams Doomguy.vpk)
    "abrams_dripbrams": "",  # # Abrams Dripbrams (Abrams Dripbrams.vpk)
    "abrams_gubami": "",  # # Abrams GUBAMI (Abrams GUBAMI.vpk)
    "abrams_hellboy": "",  # # Abrams Hellboy (Abrams Hellboy.vpk)
    "abrams_ivams": "",  # # Abrams Ivams (Abrams Ivams.vpk)
    "abrams_space_marine": "",  # # Abrams Space Marine (Abrams Space Marine.vpk)
    "abrams_zahando": "",  # # Abrams ZaHando (Abrams ZaHando.vpk)
    "demo_abram": "",  # # Demo abram (Demo abram.vpk)
    "csgo_bomb_sound": "",  # # CSGO bomb sound (CSGO bomb sound.vpk)
    "bebop_delivery": "",  # # Bebop Delivery (Bebop Delivery.vpk)
    "bebop_neon_prime_skin": "",  # # Bebop Neon Prime skin (Bebop Neon Prime skin.vpk)
    "da_purpla": "",  # # da purpla (da purpla.vpk)
    "dynamo_ult_sound": "",  # # Dinamo ult sound (Dynamo ult sound.vpk)
    "dynamo_dunkamo": "",  # # Dynamo Dunkamo (Dynamo Dunkamo.vpk)
    "hawk_tuah_charged_arrows": "",  # # Hawk tuah charged arrows (Hawk tuah charged arrows.vpk)
    "just_an_owl_drone": "",  # # Just an owl drone (Just an owl drone.vpk)
    "that_guided_owl_that_i_hate": "",  # # That Guided Owl That I Hate (That Guided Owl That I Hate.vpk)
    "svoi_talon": "",  # # Svoi Talon (Svoi Talon.vpk)
    "haze_sounds": "",  # # HAZE sounds (HAZE sounds.vpk)
    "haze_s_dagger": "",  # Haze_s dagger (Haze_s dagger.vpk)
    "haze_black+white": "",  # # Haze black+white (Haze black+white.vpk)
    "haze_checkmate": "",  # # Haze Checkmate (Haze Checkmate.vpk)
    "haze_gold": "",  # # Haze gold (Haze gold.vpk)
    "haze_ivyaze": "",  # # Haze Ivyaze (Haze Ivyaze.vpk)
    "haze_low_poly_v1": "",  # # Haze Low Poly v1 (Haze Low Poly v1.vpk)
    "haze_red": "",  # # Haze Red (Haze Red.vpk)
    "haze_silver": "",  # # Haze silver (Haze silver.vpk)
    "haze_voidwalker": "",  # # Haze VOIDWALKER (Haze VOIDWALKER.vpk)
    "holiday_v": "",  # Holiday V (Holiday V.vpk)
    "ocelot_natural": "",  # Ocelot natural (Ocelot natural.vpk)
    "ocelot_visibility": "",  # Ocelot visibility (Ocelot visibility.vpk)
    "infernus_black+white": "",  # # Infernus Black+White (Infernus Black+White.vpk)
    "infernus_scoutfernus": "",  # # Infernus Scoutfernus (Infernus Scoutfernus.vpk)
    "ivy_gardener": "",  # # Ivy Gardener (Ivy Gardener.vpk)
    "ivy_kali": "",  # # Ivy Kali (Ivy Kali.vpk)
    "ivy_low_poly": "",  # # Ivy Low Poly (Ivy Low Poly.vpk)
    "ivy's_ride_of_the_valkyries": "",  # # Ivy's Ride of the Valkyries (Ivy's Ride of the Valkyries.vpk)
    "just_a_reskin": "",  # Just a reskin (Just a reskin.vpk)
    "reskin_and_also_changes_watcher_s_covenant_to_spawn_a_small_radio_and_play_smooth_electroswing_beats": "",  # Reskin and also changes Watcher_s Covenant to spawn a small radio and play smooth electroswing beats (Reskin and also changes Watcher_s Covenant to spawn a small radio and play smooth electroswing beats.vpk)
    "kelvin_amazon_employer": "",  # # Kelvin amazon employer (Kelvin amazon employer.vpk)
    "fairy_bottle": "",  # Fairy bottle (Fairy bottle.vpk)
    "lady_geist_date": "",  # # Lady Geist Date (Lady Geist Date.vpk)
    "lady_geist_fairy": "",  # # Lady Geist Fairy (Lady Geist Fairy.vpk)
    "lady_geist_green_geist": "",  # # Lady Geist Green Geist (Lady Geist Green Geist.vpk)
    "lady_geist_rainbow": "",  # # Lady Geist Rainbow (Lady Geist Rainbow.vpk)
    "lady_geist_remgeist": "",  # # Lady Geist Remgeist (Lady Geist Remgeist.vpk)
    "lady_geist_short": "",  # # Lady Geist Short (Lady Geist Short.vpk)
    "i'm_not_gonna_sugarcoat_it": "",  # # I'm not gonna sugarcoat it (I'm not gonna sugarcoat it.vpk)
    "lash_belash": "",  # # Lash Belash (Lash Belash.vpk)
    "lash_lashton_hale_no_tshirt": "",  # # Lash Lashton Hale no Tshirt (Lash Lashton Hale no Tshirt.vpk)
    "lash_lashton_hale": "",  # # Lash Lashton Hale (Lash Lashton Hale.vpk)
    "lash_megalodon": "",  # # Lash Megalodon (Lash Megalodon.vpk)
    "lash_yakuza": "",  # # Lash Yakuza (Lash Yakuza.vpk)
    "tf2_turret_sound_replacement": "",  # # TF2 turret sound replacement (TF2 turret sound replacement.vpk)
    "turrets_from_portal": "",  # # Turrets from Portal (Turrets from Portal.vpk)
    "mcginnis_engineer": "",  # # McGinnis Engineer (McGinnis Engineer.vpk)
    "mcginnis_paw": "",  # # McGinnis Paw (McGinnis Paw.vpk)
    "mcginnis_red": "",  # # McGinnis Red (McGinnis Red.vpk)
    "mirage_s_ult_sound": "",  # # Mirage_s ult sound (Mirage_s ult sound.vpk)
    "jaws_and_krill": "",  # # Jaws and Krill (Jaws and Krill.vpk)
    "mo_and_krill_ivy_and_ivy": "",  # # Mo and Krill Ivy and Ivy (Mo and Krill Ivy and Ivy.vpk)
    "mo_and_krill_krill_and_mo": "",  # # Mo and Krill Krill and Mo (Mo and Krill Krill and Mo.vpk)
    "mo_and_krill_mo_and_mo": "",  # # Mo and Krill Mo and Mo (Mo and Krill Mo and Mo.vpk)
    "mo_and_krill_shark": "",  # # Mo and Krill Shark (Mo and Krill Shark.vpk)
    "paradox_bikinidox": "",  # # Paradox Bikinidox (Paradox Bikinidox.vpk)
    "paradox_bunnydox": "",  # # Paradox Bunnydox (Paradox Bunnydox.vpk)
    "paradox_ivydox": "",  # # Paradox Ivydox (Paradox Ivydox.vpk)
    "paradox_light_pyradox": "",  # # Paradox Light Pyradox (Paradox Light Pyradox.vpk)
    "paradox_pyradox": "",  # # Paradox Pyradox (Paradox Pyradox.vpk)
    "pocket_gold": "",  # # Pocket Gold (Pocket Gold.vpk)
    "pocket_holiday_over": "",  # # Pocket Holiday over (Pocket Holiday over.vpk)
    "pocket_loona": "",  # # Pocket Loona (Pocket Loona.vpk)
    "and_his_music_was_electric": "",  # # And his music was electric (And his music was electric.vpk)
    "better_seven_ult_sound": "",  # # Better Seven Ult Sound (Better Seven Ult Sound.vpk)
    "komm,susser_tod": "",  # # Komm,susser Tod (Komm,susser Tod.vpk)
    "my_love_mine_all_mine": "",  # # My Love Mine All Mine (My Love Mine All Mine.vpk)
    "rammstein_sonne": "",  # # Rammstein Sonne (Rammstein Sonne.vpk)
    "seven_gigavatt": "",  # # Seven gigavatt (Seven gigavatt.vpk)
    "seven_halloween": "",  # # Seven Halloween (Seven Halloween.vpk)
    "seven_low_poly": "",  # # Seven Low Poly (Seven Low Poly.vpk)
    "seven_neonprime": "",  # # Seven NeonPrime (Seven NeonPrime.vpk)
    "shiv_bald": "",  # # Shiv Bald (Shiv Bald.vpk)
    "shiv_infernus_cap": "",  # # Shiv Infernus Cap (Shiv Infernus Cap.vpk)
    "shiv_long_hair": "",  # # Shiv Long hair (Shiv Long hair.vpk)
    "shiv_neon_prime": "",  # # Shiv Neon Prime (Shiv Neon Prime.vpk)
    "shiv_v": "",  # # Shiv V1 (Shiv V.vpk)
    "awp_sound_ult": "",  # # awp sound ult (awp sound ult.vpk)
    "vindicta_bikinidicta_full_mod": "",  # # Vindicta Bikinidicta Full mod (Vindicta Bikinidicta Full mod.vpk)
    "vindicta_bikinidicta_no_2_skill_music": "",  # # Vindicta Bikinidicta No 2 skill music (Vindicta Bikinidicta No 2 skill music.vpk)
    "vindicta_bikinidicta_no_sounds": "",  # # Vindicta Bikinidicta No sounds (Vindicta Bikinidicta No sounds.vpk)
    "vindicta_black+white": "",  # # Vindicta Black+White (Vindicta Black+White.vpk)
    "vindicta_ivydicta": "",  # # Vindicta Ivydicta (Vindicta Ivydicta.vpk)
    "vindicta_sandals": "",  # # Vindicta Sandals (Vindicta Sandals.vpk)
    "vindicta_shoes": "",  # # Vindicta Shoes (Vindicta Shoes.vpk)
    "vindicta_widowmaker": "",  # # Vindicta Widowmaker (Vindicta Widowmaker.vpk)
    "viper_makes_viper_sounds": "",  # # Viper makes viper sounds (Viper makes viper sounds.vpk)
    "viper_snake": "",  # # Viper snake (Viper snake.vpk)
    "viscous_cumcous": "",  # # Viscous Cumcous (Viscous Cumcous.vpk)
    "viscous_glorp": "",  # # Viscous Glorp (Viscous Glorp.vpk)
    "viscous_halloween": "",  # # Viscous Halloween (Viscous Halloween.vpk)
    "viscous_pink": "",  # # Viscous Pink (Viscous Pink.vpk)
    "viscous_raspberry": "",  # # Viscous Raspberry (Viscous Raspberry.vpk)
    "viscous_viscoast": "",  # # Viscous Viscoast (Viscous Viscoast.vpk)
    "wraith_black+white": "",  # # Wraith Black+White (Wraith Black+White.vpk)
    "wraith_without_cloak": "",  # # Wraith Without cloak (Wraith Without cloak.vpk)
    "yamato_ult_demonic_voice_filter": "",  # # Yamato Ult Demonic Voice Filter (Yamato Ult Demonic Voice Filter.vpk)
    "yamato_2b_without_drawn_sword_and_skirt": "",  # # Yamato 2B without drawn sword and skirt (Yamato 2B without drawn sword and skirt.vpk)
    "yamato_2b_without_drawn_sword": "",  # # Yamato 2B without drawn sword (Yamato 2B without drawn sword.vpk)
    "yamato_2b_without_skirt": "",  # # Yamato 2B without skirt (Yamato 2B without skirt.vpk)
    "yamato_2b": "",  # # Yamato 2B (Yamato 2B.vpk)
    "yamato_mytrato": "",  # # Yamato Mytrato (Yamato Mytrato.vpk)
    "yamato_neonprime": "",  # # Yamato NeonPrime (Yamato NeonPrime.vpk)
    "yamato_raiden": "",  # # Yamato Raiden (Yamato Raiden.vpk)
    "yamato_vegil": "",  # Yamato Vegil (Yamato Vegil.vpk)
    "yamato_vergil": "",  # # Yamato Vergil (Yamato Vergil.vpk)

    # INTERFACE
    "43_ratio_healthbar_fix": "",  # # 43 ratio healthbar fix (43 ratio healthbar fix.vpk)
    "4x3_fix_shop": "",  # # 4x3 fix shop (4x3 fix shop.vpk)
    "among_us_(hud_mod)": "",  # # Among Us (HUD mod) (Among Us (HUD mod).vpk)
    "better_dot_add-on": "",  # # Better dot add-on (Better dot add-on.vpk)
    "deadlock_relit": "",  # # Deadlock Relit (Deadlock Relit.vpk)
    "deadlock_toasted": "",  # # Deadlock Toasted (Deadlock Toasted.vpk)
    "dumblock_custom_icons": "",  # # DumbLock Custom icons (DumbLock Custom icons.vpk)
    "moglock_(portrait_mod)": "",  # # Moglock (portrait mod) (Moglock (portrait mod).vpk)
    "old_minimap_icons": "",  # # old minimap icons (old minimap icons.vpk)
    "robo's_deadlock_portraits": "",  # # robo's Deadlock Portraits (robo's Deadlock Portraits.vpk)
    "square_top_bar": "",  # # Square Top Bar (Square Top Bar.vpk)

    # POST-PROCESSING
    "deer's_post_processing": "",  # # deer's post processing (deer's post processing.vpk)
    "lamarrite_s_post_processing": "",  # # lamarrite_s post processing (lamarrite_s post processing.vpk)
    "mega's_post_processing": "",  # # Mega's post processing (Mega's post processing.vpk)

    # SOUNDS
    "banana_knockdown": "",  # # Banana knockdown (Banana knockdown.vpk)
    "ebaniy_rot_etogo_kazino": "",  # # Ebaniy rot etogo kazino (Ebaniy rot etogo kazino.vpk)
    "flashbang": "",  # # Flashbang (Flashbang.vpk)
    "heavy_attack_alert": "",  # # Heavy attack alert (Heavy attack alert.vpk)
    "killstreak_sounds_with_dota_announcer": "",  # # Killstreak sounds with Dota Announcer (Killstreak sounds with Dota Announcer.vpk)
    "laugh_track_getting_denied_sounds": "",  # # Laugh track getting denied sounds (Laugh track getting denied sounds.vpk)
    "musical_modification_by_rymskiy": "",  # # Musical Modification by RYMSKIY (Musical Modification by RYMSKIY.vpk)
    "quake_live_champions_sound_mod": "",  # # Quake Live Champions Sound Mod (Quake Live Champions Sound Mod.vpk)
    "resampled_refresher_sound": "",  # # Resampled Refresher Sound (Resampled Refresher Sound.vpk)
    "risk_of_rain_music_pack": "",  # # Risk of Rain Music Pack (Risk of Rain Music Pack.vpk)
    "sounds_of_death": "",  # # Sounds of death (Sounds of death.vpk)
    "the_silly_killsounds": "",  # # The Silly Killsounds (The Silly Killsounds.vpk)

}
